name: Build the CV and deploy on GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Compile CV
        uses: xu-cheng/latex-action@4.0.0
        with:
          root_file: cv.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v4.6.2
        with:
          name: cv.pdf
          path: build/cv.pdf

  deploy:
    needs: build

    concurrency:
      group: "pages"
      cancel-in-progress: false

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download PDF
        uses: actions/download-artifact@v5.0.0
        with:
          name: cv.pdf
          path: github-pages/

      - name: Copy static content
        run: |
          mkdir -p github-pages/
          cp -r static/* github-pages/

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: github-pages/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
